In [1]:
import numpy as np

In [5]:
a = np.array([[1, 2, 3],[4,5,6]])

In [6]:
a.shape

(2, 3)

Array fundamentals

In [7]:
a = np.array([1, 2, 3, 4, 5, 6])

In [8]:
a

array([1, 2, 3, 4, 5, 6])

In [10]:
a[0]

np.int64(1)

In [11]:
a[0]=10

In [12]:
a

array([10,  2,  3,  4,  5,  6])

In [13]:
a[:3]

array([10,  2,  3])

In [15]:
b=a[3:]
b

array([4, 5, 6])

In [16]:
b[0]=40
a

array([10,  2,  3, 40,  5,  6])

In [19]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
a[1,3]

np.int64(8)

Array attributes

In [21]:
a.ndim

2

In [22]:
a.shape

(3, 4)

In [23]:
len(a.shape) == a.ndim

True

In [24]:
a.size

12

In [25]:
import math

In [26]:
a.size == math.prod(a.shape)

True

In [27]:
a.dtype

dtype('int64')

How to create a basic array

In [28]:
np.zeros(2)

array([0., 0.])

In [29]:
np.ones(2)

array([1., 1.])

In [30]:
np.empty(2)

array([1., 1.])

In [32]:
np.empty(2)

array([1., 1.])

In [34]:
np.arange(4)

array([0, 1, 2, 3])

In [35]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [36]:
np.linspace(0,19,num=5)

array([ 0.  ,  4.75,  9.5 , 14.25, 19.  ])

In [38]:
x=np.ones(2,dtype=np.int64)
x

array([1, 1])

Adding, removing, and sorting elements

In [39]:
arr=np.array([2,1,5,3,7,4,6,8])

In [40]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

How do you know the shape and size of an array

In [46]:
array_example=np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]]])
array_example.ndim

3

In [47]:
array_example.size

24

In [48]:
array_example.shape

(3, 2, 4)

Can you reshape an array

In [49]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [50]:
b=a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [51]:
np.reshape(a,shape=(1,6),order='c')

array([[0, 1, 2, 3, 4, 5]])

How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [52]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [53]:
a2=a[np.newaxis,:]
a2.shape

(1, 6)

In [54]:
row_vector=a[np.newaxis,:]
row_vector.shape

(1, 6)

In [55]:
col_vector=a[:,np.newaxis]
col_vector.shape

(6, 1)

In [56]:
b=np.expand_dims(a,axis=1)
b.shape

(6, 1)

In [57]:
c=np.expand_dims(a,axis=0)
c.shape

(1, 6)

Indexing and slicing

In [58]:
data=np.array([1,2,3])

In [59]:
data[1]

np.int64(2)

In [60]:
data[0:2]

array([1, 2])

In [61]:
data[1:]

array([2, 3])

In [62]:
data[-2:]

array([2, 3])

In [63]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [64]:
print(a[a<5])

[1 2 3 4]


In [65]:
five_up=(a>=5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [66]:
divisible_by_2=a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [67]:
c=a[(a>2)&(a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [70]:
five_up=(a>5)|(a==5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [71]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [74]:
b=np.nonzero(a<5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [75]:
list_of_coordinates=list(zip(b[0],b[1]))

In [76]:
for coord in list_of_coordinates:
    print (coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [77]:
print(a[b])

[1 2 3 4]


In [78]:
not_there=np.nonzero(a==42)

In [79]:
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


How to create an array from existing data

In [80]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr1=a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [84]:
a1=np.array([[1,1],[2,2]])
a2=np.array([[3,3],[4,4]])
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [85]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [86]:
x=np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [87]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [88]:
np.hsplit(x,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [89]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [92]:
b1=a[0,:]
b1

array([1, 2, 3, 4])

In [94]:
b1[0]=99
b1

array([99,  2,  3,  4])

In [95]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
b2=a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Basic array operations

In [98]:
data=np.array([1,2])
ones=np.ones(2,dtype=int)
data+ones

array([2, 3])

In [99]:
data-ones

array([0, 1])

In [101]:
data*data

array([1, 4])

In [102]:
data/data

array([1., 1.])

In [103]:
a=np.array([1,2,3,4])
a.sum()

np.int64(10)

In [104]:
b=np.array([[1,1],[2,2]])
b.sum(axis=0)

array([3, 3])

In [105]:
b.sum(axis=1)

array([2, 4])

Broadcasting

In [106]:
data=np.array([1.0,2.0])
data*1.6

array([1.6, 3.2])

More useful array operations

In [107]:
data=np.array([1,2,3])
data.max()

np.int64(3)

In [108]:
data.min()

np.int64(1)

In [109]:
data.sum()

np.int64(6)

In [110]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [111]:
a.sum()

np.float64(4.8595784)

In [112]:
a.min()

np.float64(0.05093587)

In [113]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [114]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

Creating matrices

In [115]:
data=np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [116]:
data[0,1]

np.int64(2)

In [117]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [118]:
data[0:2,0]

array([1, 3])

In [119]:
data.max()

np.int64(6)

In [120]:
data.min()

np.int64(1)

In [121]:
data.sum()

np.int64(21)

In [122]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [123]:
data.max(axis=0)

array([5, 6])

In [124]:
data.max(axis=1)


array([2, 5, 6])

In [126]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data+ones

array([[2, 3],
       [4, 5]])

In [127]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data+ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [128]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [129]:
np.ones(3)

array([1., 1., 1.])

In [130]:
np.zeros(3)

array([0., 0., 0.])

In [132]:
rng = np.random.default_rng()
rng.random(3) 

array([0.20172302, 0.22799639, 0.8645889 ])

In [133]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [134]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [135]:
rng.random((3, 2)) 

array([[0.85104105, 0.47615039],
       [0.71370878, 0.84330879],
       [0.41168978, 0.93649167]])

Generating random numbers

In [136]:
rng.integers(5, size=(2, 4)) 

array([[4, 0, 0, 4],
       [2, 3, 2, 1]])

How to get unique items and counts

In [137]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [138]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [139]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [140]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [141]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [142]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [143]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [144]:
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)

In [146]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [147]:
print(indices)

[0 1 2]


In [148]:
print(occurrence_count)

[2 1 1]


Transposing and reshaping a matrix

In [149]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [150]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [151]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [152]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [153]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

How to reverse an array

In [155]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr=np.flip(arr)
reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1])

In [156]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr=np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [157]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [161]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
reversed_arr_columns

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [162]:
arr_2d[1] = np.flip(arr_2d[1])
arr_2d

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [163]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
arr_2d

array([[ 1, 10,  3,  4],
       [ 8,  7,  6,  5],
       [ 9,  2, 11, 12]])

Reshaping and flattening multidimensional arrays

In [165]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [166]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [167]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [168]:
a2 = x.ravel()
a2[0]=98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [169]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
